/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: acd551d9ebc5f47cb4146c18e34ddda0)
interface __BaseEnv_Env {
	DB: D1Database;
	AI_SEARCH: AiSearchNamespace;
	AI: Ai;
	ASSETS: Fetcher;
	ADMIN_EMAILS: "vladi.acg@gmail.com";
	APP_ORIGIN: "https://lugarerrado.com";
	APP_ORIGINS: "https://lugarerrado.com,https://cursorvetolight.vladi-acg.workers.dev";
	GOOGLE_CLIENT_ID: "1074979364289-lrn10t4t84eb3p1o2lcs8iiv7hsbjmeh.apps.googleusercontent.com";
	GOOGLE_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_EMAILS" | "APP_ORIGIN" | "APP_ORIGINS" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET">> {}
}
